version: '3.2'

services:
    traefik:
        image: traefik
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        command: --api --docker --docker.swarmMode --docker.watch 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: replicated
            replicas: 1 
            placement:
                constraints: [node.role == manager]
      
    nginx:
        image: nginx:1.16.0
        volumes:
            - /home/bijay/docker-swarm-mode/server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /home/bijay/docker-swarm-mode/www:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == worker]
        labels:
                              #   - traefik.docker.network=lemp_default
            - traefik.frontend.rule=Host:localhost
            - traefik.backend=nginx
            - traefik.port=80
            
    php:
        build: ./server
        image: php-mysqli:7-fpm
        volumes:
            - /home/bijay/docker-swarm-mode/server/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - /home/bijay/docker-swarm-mode/www:/var/www/html
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == worker]
           
    mysql:
        image: mysql:5.7     
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root    
        volumes:
            - /home/bijay/docker-swarm-mode/mysql/data:/var/lib/mysql
            - /home/bijay/docker-swarm-mode/mysql/dumps:/docker-entrypoint-initdb.d
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == manager]
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8000:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        deploy:
            mode: replicated    
            replicas: 1
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == manager]