version: '3.2'

services:
    nginx:
        image: nginx:1.16.0
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"  
        volumes:
            - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./www:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt
        links:
            - php
            - mysql
        
    php:
        build: ./server
        image: php
        container_name: php
        restart: always
        volumes:
            - ./server/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./www:/var/www/html
           
    mysql:
        image: mysql:5.7
        container_name: mysql       
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root    
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/dumps:/docker-entrypoint-initdb.d
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - "8000:80"
        environment:
            MYSQL_ROOT_PASSWORD: root
        links: 
            - mysql:db