version: '3.2'

services:
    nginx:
        image: nginx:1.16.0
        ports:
            - "80:80"
            - "443:443"  
        volumes:
            - /home/bijay/docker-swarm-mode/server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /home/bijay/docker-swarm-mode/www:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 90s
            
    php:
        image: php:7-fpm
        volumes:
            - /home/bijay/docker-swarm-mode/server/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - /home/bijay/docker-swarm-mode/www:/var/www/html
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 90s
           
    mysql:
        image: mysql:5.7     
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root    
        volumes:
            - /home/bijay/docker-swarm-mode/mysql/data:/var/lib/mysql
            - /home/bijay/docker-swarm-mode/mysql/dumps:/docker-entrypoint-initdb.d
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 90s
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8000:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 90s