version: '3.2'

services:
    nginx:
        image: nginx:1.16.0
        ports:
            - "80:80"
            - "443:443"  
        volumes:
            - /home/bijay/docker-swarm-mode/server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /home/bijay/docker-swarm-mode/www:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - php
            - mysql
        networks:
            - services
        deploy:
            mode: global
            restart_policy:
                condition: unless-stopped
            
    php:
        image: php:7-fpm
        volumes:
            - /home/bijay/docker-swarm-mode/server/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - /home/bijay/docker-swarm-mode/www:/var/www/html
        networks:
            - services
        deploy:
            mode: global
            restart_policy:
                condition: unless-stopped
           
    mysql:
        image: mysql:5.7     
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root    
        volumes:
            - /home/bijay/docker-swarm-mode/mysql/data:/var/lib/mysql
            - /home/bijay/docker-swarm-mode/mysql/dumps:/docker-entrypoint-initdb.d
        networks:
            - services
        deploy:
            mode: global
            restart_policy:
                condition: unless-stopped
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8000:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - services
        deploy:
            mode: global
            restart_policy:
                condition: unless-stopped
            
networks:
    services: