version: '3.7'

services:    
    mysql:
        image: bitnami/mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - /home/bijay/mysql/data:/bitnami/mysql/data
            - /home/bijay/mysql/dumps:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: EhxTp7k7UpWQ9x8
            MYSQL_DATABASE: pctech
            MYSQL_USER: bijay
            MYSQL_PASSWORD: 12345
            MYSQL_REPLICATION_MODE: master
            MYSQL_REPLICATION_USER: rep_user
            MYSQL_REPLICATION_PASSWORD: 56789
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == manager]
        networks:
            - docker_default 
            
    mysql-replica:
        image: bitnami/mysql:5.7
        volumes:
            - /home/bijay/mysql/data:/bitnami/mysql/data
            - /home/bijay/mysql/dumps:/docker-entrypoint-initdb.d
        environment:
            MYSQL_MASTER_HOST: mysql
            MYSQL_MASTER_PORT_NUMBER: 3306
            MYSQL_MASTER_ROOT_PASSWORD: EhxTp7k7UpWQ9x8
            MYSQL_REPLICATION_MODE: slave
            MYSQL_REPLICATION_USER: rep_user
            MYSQL_REPLICATION_PASSWORD: 56789
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == worker]
        networks:
            - docker_default

networks:
    docker_default:
        external: true            