version: '3.2'

services:
    portainer:
        image: portainer/portainer
        command: -H tcp://tasks.agent:9001 --tlsskipverify
        ports:
            - "9000:9000"
        volumes:
            - data:/data
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
                
    agent:
        image: portainer/agent:1.1.2
        environment:
            AGENT_CLUSTER_ADDR: tasks.agent
                             # LOG_LEVEL: debug
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        deploy:
            mode: global
            
volumes:
    data: