version: '3.7'

services:
    redis-sentinel:
        image: redis
        command: redis-server --sentinel --sentinel monitor mymaster redis 6379 2
        deploy:
            mode: global
            restart_policy:
                max_attempts: 5
        networks:
            - docker_default
    redis:
        image: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - /home/bijay/docker-swarm-mode/server/redis/redis-master.conf:/usr/local/etc/redis/redis.conf
            - /home/bijay/redis-data:/data
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == manager]
        networks:
            - docker_default 
    
    redis-replica:
        image: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - /home/bijay/docker-swarm-mode/server/redis/redis-replica.conf:/usr/local/etc/redis/redis.conf
            - /home/bijay/redis-data:/data
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == worker]
        networks:
            - docker_default 
             
networks:
    docker_default:
        external: true