version: '3.7'

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        volumes:
            - /home/bijay/redis:/data
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                max_attempts: 5
            placement:
                constraints: [node.role == manager]
        networks:
            - docker_default 
            
networks:
    docker_default:
        external: true