version: '3.7'

services:
    repcached:
        image: oktec/repcached
        restart: always
        ports:
            - "127.0.0.1:11211:11211"
            - "11212:11212"
        environment:
            - SLAVE="139.162.42.173"
        networks:
            - docker_default 
            
networks:
    docker_default:
        external: true